version: "3"

# this docker compose only be use to build an production image
# do not up this docker compose, only build

services:
  nginx:
    image: asia-southeast1-docker.pkg.dev/uvdesk-demo-393909/docker/nginx/tekno:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/ssl/etc/letsencrypt:/etc/letsencrypt/
    environment:
      - DISABLE_IPV6=true

  db:
    image: mysql:latest
    volumes:
      - ./mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: uvdesk
      MYSQL_ROOT_PASSWORD: teknoniaga2023
      MYSQL_USER: uvdesk
      MYSQL_PASSWORD: teknoniaga2023

  uvdesk:
    image: asia-southeast1-docker.pkg.dev/uvdesk-demo-393909/docker/uvdesk/tekno:latest
    tty: true
    environment:
      DATABASE_URL: mysql://uvdesk:teknoniaga2023@db:3306/uvdesk
      APP_ENV: prod
      SITE_URL: istananegara.teknoniaga.com.my
      # MAILER_URL: smtp://56c1c41b5ea1ee:27f59daab398cf@sandbox.smtp.mailtrap.io:2525
    # volumes:
    #   - ./:/var/www
