version: "3"
services:
  nginx:
    image: nginx:alpine
    container_name: tekno-uvdesk-nginx
    depends_on:
      - uvdesk
      - db
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443 #https
    volumes:
      - ./:/var/www
      - ./docker/nginx/ssl.conf:/etc/nginx/conf.d/tekno.conf
      - ./docker/nginx/ssl/etc/letsencrypt/:/etc/letsencrypt/
      # - ssl_cert:/etc/letsencrypt #ssl cert
    environment:
      - DISABLE_IPV6=true

  db:
    image: mysql:latest
    volumes:
      - ./mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: uvdesk
      MYSQL_ROOT_PASSWORD: teknoniaga2023
      MYSQL_USER: uvdesk
      MYSQL_PASSWORD: teknoniaga2023

  uvdesk:
    image: tekno/uvdesk-app:dev
    build:
      args:
        user: sammy
        uid: 1000
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    tty: true
    environment:
      DATABASE_URL: mysql://uvdesk:teknoniaga2023@db:3306/uvdesk
      APP_ENV: dev
      # MAILER_URL: smtp://56c1c41b5ea1ee:27f59daab398cf@sandbox.smtp.mailtrap.io:2525
    # volumes:
    #   - ./:/var/www
