version: "3"
services:
  nginx:
    image: asia-southeast1-docker.pkg.dev/uvdesk-demo-393909/docker/nginx/tekno:profile
    container_name: tekno-uvdesk-nginx
    depends_on:
      - uvdesk
      - db
    restart: unless-stopped
    ports:
      - 80:80
      # - 443:443 #https
    environment:
      - DISABLE_IPV6=true

  db:
    image: mysql:latest
    volumes:
      - ./mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: uvdesk
      MYSQL_ROOT_PASSWORD: teknoniaga2023
      MYSQL_USER: uvdesk
      MYSQL_PASSWORD: teknoniaga2023

  uvdesk:
    image: asia-southeast1-docker.pkg.dev/uvdesk-demo-393909/docker/uvdesk/tekno:profile
    depends_on:
      - db
    tty: true
    environment:
      DATABASE_URL: mysql://uvdesk:teknoniaga2023@db:3306/uvdesk
      APP_ENV: dev
      SITE_URL: istana.labkami.com.my
      # MAILER_URL: smtp://56c1c41b5ea1ee:27f59daab398cf@sandbox.smtp.mailtrap.io:2525
